### ISSUE TITLE
rmagickの画像保存名を毎回変える

### ISSUE THREAD

**Issue by tomoharutsutsumi** [tomoharutsutsumi/prize#19]

**Comment by tomoharutsutsumi** [comment]
こんな形でどうでしょう。
count_numbersというメソッドを追加。数値を戻り値とし、
その番号を一つ一つの画像にくっつける。。。。というもので考えました。

```award.rb

def upload_aws
    Aws.config.update({
    credentials: Aws::Credentials.new(ENV['ACCESS_KEY_ID'], ENV['SECRET_ACCESS_KEY'])})
    s3 = Aws::S3::Resource.new(region: 'ap-northeast-1')
    bucket = s3.bucket('prize-object')
    count_numbers
    object = bucket.object("#{number}-award.png")
    object.upload_file("annotated_award_img.png")
end

def count_numbers
    if Award.exists?
      number = Award.last.id + 1
    else
      number = 1
    end
end

```

まだ動作検証はしていないです。

**Comment by ms2sato** [comment]
@tomoharutsutsumi 確認です。この実装をした場合の、AwardのIDと、numberの関係を書いてみてください。

**Comment by tomoharutsutsumi** [comment]
@ms2sato
saveの前の確認画面で画像生成されるので、
新しく生成されたawardのidが１ならば（正確には保存されていないので、idが１になる予定）　numberも１
上記idが２ならば　numberも２だと思います。

**Comment by ms2sato** [comment]
@tomoharutsutsumi OK。イメージは大丈夫そう。

で、もしもそれが不安なら、先に一回保存するのはどうかな？先にIDを確定させて、それを利用すればnumberは必ずIDと一致させられるよね。

他の方法としては、先にランダムな名前を作るようにして、Awardと一緒に保存する形かな。カラムをuniqueにしておけば名前が被らなくなるし、保存前に一意かどうかチェックするコードを入れる形。
